name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install 'jupyterlab>=3.0.0'
    - name: Build the extension
      run: |
        set -x
        jlpm
        jlpm run eslint:check
        python -m pip install .

        jupyter serverextension list 2>&1 | grep -ie "ipyspaghetti.*OK"

        jupyter labextension list 2>&1 | grep -ie "ipyspaghetti.*OK"
        python -m jupyterlab.browser_check
        set +x
